Repository creativeplatform/curly-spork, pull requests merged in 2023-01, with the labels that each got.

#2 Header Updates
  .gitignore
  next.config.js
  package.json
  src/assets/creative-logo.svg
  src/assets/radiate_warrior.png
  src/components/layout/Header.tsx
  src/utils/config.ts
  yarn.lock
Labels: bug

#3 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#5 Feat/lens integration
  codegen.yml
  package.json
  src/components/SignInButton.tsx
  src/components/layout/Header.tsx
  src/graphql/add-reaction.graphql
  src/graphql/auth-fetcher.ts
  src/graphql/authenticate.graphql
  src/graphql/challenge.graphql
  src/graphql/comment.graphql
  src/graphql/common.graphql
  src/graphql/explore-publications.graphql
  src/graphql/follow.graphql
  src/graphql/followers.graphql
  src/graphql/following.graphql
  src/graphql/generated.ts
  src/graphql/get-default-profile.graphql
  src/graphql/get-profile.graphql
  src/graphql/post.graphql
  src/graphql/refresh.graphql
  src/lib/auth/generateChallenge.ts
  src/lib/auth/helpers.ts
  src/lib/auth/refreshAccessToken.ts
  src/lib/auth/useLensUser.ts
  src/lib/auth/useLogin.ts
  src/lib/helpers.ts
  src/lib/useFollow.ts
  src/pages/_app.tsx
  src/pages/profile/[id].tsx
  src/utils/config.ts
  yarn.lock
Labels: enhancement

#10 Footer
  .gitignore
  codegen.yml
  next.config.js
  package.json
  src/assets/creative-logo.svg
  src/assets/radiate_warrior.png
  src/components/SignInButton.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeroSection.tsx
  src/components/layout/index.tsx
  src/graphql/add-reaction.graphql
  src/graphql/auth-fetcher.ts
  src/graphql/authenticate.graphql
  src/graphql/challenge.graphql
  src/graphql/comment.graphql
  src/graphql/common.graphql
  src/graphql/explore-publications.graphql
  src/graphql/follow.graphql
  src/graphql/followers.graphql
  src/graphql/following.graphql
  src/graphql/generated.ts
  src/graphql/get-default-profile.graphql
  src/graphql/get-profile.graphql
  src/graphql/post.graphql
  src/graphql/refresh.graphql
  src/lib/auth/generateChallenge.ts
  src/lib/auth/helpers.ts
  src/lib/auth/refreshAccessToken.ts
  src/lib/auth/useLensUser.ts
  src/lib/auth/useLogin.ts
  src/lib/helpers.ts
  src/lib/useFollow.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/profile/[id].tsx
  src/utils/config.ts
  yarn.lock
Labels: enhancement

#13 Remove thirdweb
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
  package.json
  src/assets/radiate_warrior.png
  src/components/SignInButton.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeroSection.tsx
  src/components/layout/index.tsx
  src/pages/_app.tsx
  src/pages/profile/[id].tsx
  yarn.lock
Labels: bug, enhancement

#15 bug fix
  package.json
  yarn.lock
Labels: bug

#19 Featured video section
  src/components/Featured.tsx
  src/components/HeroSection.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Head.tsx
  src/components/layout/Header.tsx
  src/components/layout/SignInButton.tsx
  src/components/layout/index.tsx
  src/pages/_app.tsx
  src/pages/discover.tsx
  src/pages/index.tsx
  src/utils/config.ts
  yarn.lock
Labels: bug, enhancement

#18 Staging
  package.json
  src/components/Featured.tsx
  src/components/HeroSection.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Head.tsx
  src/components/layout/Header.tsx
  src/components/layout/SignInButton.tsx
  src/components/layout/index.tsx
  src/lib/helpers.ts
  src/lib/useFollow.ts
  src/pages/_app.tsx
  src/pages/discover.tsx
  src/pages/index.tsx
  src/pages/profile/[id].tsx
  src/utils/config.ts
  src/utils/context.ts
  yarn.lock
Labels: bug, enhancement

#20 feat: hide and show content based on status of unlock protocol locks
  package.json
  src/hooks/useLock.tsx
  src/lib/auth/useLogin.ts
  src/pages/examples/token-gate.tsx
  yarn.lock
Labels: enhancement

#21 polygon connect
  src/pages/_app.tsx
  src/providers/Web3.tsx
  src/utils/config.ts
  src/utils/network.ts
  yarn.lock
Labels: bug, enhancement
